apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        #volumeMounts:
        #- name: mysql
        #  mountPath: "/Users/3r1ck/Documents/Dockers/Zabbix/mysql-volume"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "Z4bb1x123"
