apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix
  labels:
    app: zabbix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: zabbix
    spec:
      containers:
      - name: zabbix
        image: zabbix/zabbix-server-mysql
        ports:
        - containerPort: 80
        #volumeMounts:
        #- name: mysql
        #  mountPath: "/Users/3r1ck/Documents/Dockers/Zabbix/mysql-volume"
        env:
        - name: DB_SERVER_HOST
          value: "mysql"
        - name: DB_SERVER_PORT
          value: "3306"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "Z4bb1x123"
        - name: MYSQL_DATABASE
          value: "zabbix"
